FROM eclipse-temurin:17

RUN apt-get update && \
    apt-get install --no-install-recommends -y git && \
    rm -rf /var/lib/apt/lists/*

COPY worker/run-worker.sh /run-worker.sh

WORKDIR /

CMD ["/run-worker.sh"]
